apiVersion: v1
kind: Pod
metadata:
  name: testapp
  namespace: devproject
spec:
  containers:
  - name: testcon
    image: sudarshanlnx/farmfresh:v1
    imagePullPolicy: Always
    ports: 
    - containerPort: 80
      name: apache
      protocol: TCP
    resources:
      requests:
        memory: "100mi"
        cpu: "100m"
      limits: 
        memory: "200mi"
        cpu: "200m"
